---
title: "EEB313 - Final Project"
Authors: Queenny Chiu, Anna Ly, Derek Lau
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(lmerTest)
library(lme4)
library(MuMIn)
library(ggpubr)
```

```{r}
mingan_flower_data <- read_csv("mingan_flower_data.csv")
head(mingan_flower_data)

mingan_weather_data <- read_csv("mingan_weather_data.csv")
head(mingan_weather_data)
```

```{r}
#changing the column name "survey_year" into "year"
colnames(mingan_flower_data)[5] <- "year"
```

```{r}
#make columns with year, month, day
dmy_weather<-mingan_weather_data %>%
mutate(date=dmy(date),
  year=lubridate::year(date),
  month=lubridate::month(date),
  day=lubridate::day(date))
dmy_weather
```

```{r}
#make column with average humidity for each month (between April and July) for each year
avg_weather <- dmy_weather%>%
  filter(month >= 4 & month <= 7 & !is.na(avg_relative_humidity) & 
           !is.na(avg_temperature)) %>% 
  group_by(month, year) %>%
  summarise(mean_avg_relative_humidity=mean(avg_relative_humidity),
            mean_avg_temp=mean(avg_temperature))
avg_weather
```

```{r}
#plot average temperature vs. average relative humidity (between April and July)
temp_humidity <- ggscatter(avg_weather, x = "mean_avg_temp", y = "mean_avg_relative_humidity", 
                           add = "reg.line", conf.int = TRUE, 
                           cor.method = "kendall",
          xlab = "Average Temperature (Degrees Celsius)", ylab = "Average Relative Humidity (%)")
temp_humidity
```


```{r}
#validate assumptions for correlation test

#1 - linearity --> linearity is shown in the plot above

#2 - normality (Shapiro-Wilk Test and qqplot)
#temperature normality
shapiro.test(avg_weather$mean_avg_temp) 
ggqqplot(avg_weather$mean_avg_temp, ylab = "Average Temperature")
#temperature p-value < 0.05, so normality assumption is invalid --> use Spearman or Kendall

#humidity normality
shapiro.test(avg_weather$mean_avg_relative_humidity)
ggqqplot(avg_weather$mean_avg_relative_humidity, ylab = "Average Relative Humidity")
```


```{r}
# Running a correlation test between average temperature and average relative humidity
cor.test(avg_weather$mean_avg_relative_humidity, avg_weather$mean_avg_temp, method = "spearman")
#Spearman cannot compute exact p-value with ties, so use kendall
cor.test(avg_weather$mean_avg_relative_humidity, avg_weather$mean_avg_temp, method = "kendall")
```





```{r}
# find average temperature per year
mean_annual_temp <- avg_weather %>% 
  group_by(year) %>% 
  summarise(mean_annual_temp = mean(mean_avg_temp))

mean_annual_temp
```

```{r}
mean_annual_temp <- avg_weather %>% 
  group_by(year) %>% 
  summarise(mean_annual_temp = mean(mean_avg_temp))
mean_annual_temp
```

```{r}
#merge the two data into one
total <- merge(mingan_flower_data, mean_annual_temp, by="year")
total
```

```{r}
#filter out NAs
flower_temp_data <- total %>% 
  filter(!is.na(day))

flower_temp_data
```

```{r}
#Model 1: first flowering date vs. temperature based on actual data
flower_temp_data %>% 
  ggplot(aes(x = mean_annual_temp, y = day)) +
  geom_smooth(method = "lm")+
  geom_point()+
  theme_classic() +
  labs(title = "First Flowering Date vs. Temperature", x = "Mean Annual Temperature (Degrees Celsius)", y = "First Flowering Date (Actual Data)" )
```

```{r}
#Model 1 (y = flowering day, x = temperature)
lm1 <- lm(day~mean_annual_temp, data=flower_temp_data)
summary(lm1)
```
#p-value = 0.01275 --> Since p-value < 0.05, temperature has a significant effect on first flowering date.

```{r}
#Model 1: validate assumptions
plot(lm1, 1:2)
```
# Residuals vs. Fitted plot --> homogeneity of variances at each X is met
# Normal Q-Q --> data is normally distributed

```{r}
#Model 2: first flowering date vs. species based on actual data
flower_temp_data %>% 
  ggplot(aes(x = species_name, y = day, fill = species_name)) +
  geom_boxplot()+
  theme_classic() +
  labs(title = "First Flowering Date vs. Species", x = "Species", y = "First Flowering Date (Actual Data)" )
```

```{r}
#Model 2 (y = flowering day, x = species)
lm2 <- lm(day~species_name, data=flower_temp_data)
summary(lm2)

```

```{r}
#Model 2: validate assumptions
plot(lm2, 1:2)
```

```{r}
# create graph of temperature (x) vs. flowering day (y) by species using actual data

flower_temp_data %>% 
  group_by(mean_annual_temp, species_name) %>% 
  ggplot(aes(x = mean_annual_temp, y = day, colour = species_name)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_classic() +
  labs(title = "First Flowering Date vs. Temperature (by Species)", x = "Mean Annual Temperature (Degrees Celsius)", y = "First Flowering Date (Actual Data)" )
```


```{r}
#Model 3 (y = flowering day, x = temperature*species)
lm3 <- lm(day~mean_annual_temp*species_name, data=flower_temp_data)
summary(lm3)

```

```{r}
#Model 3: validate assumptions
plot(lm3, 1:2)
```

# RANDOM EFFECT A: (1|station_name)

```{r}
#Model 1.a (flowering date vs. temperature + stations (RANDOM EFFECT))

lm1.a <- lmer(day ~ mean_annual_temp + (1|station_name), data = flower_temp_data, REML = FALSE)   
summary(lm1.a)
```

```{r}
#Model 2.a (flowering date vs. species + stations (RANDOM EFFECT))

lm2.a <- lmer(day ~ species_name + (1|station_name), data = flower_temp_data, REML = FALSE)   
summary(lm2.a)
```

```{r}
#Model 3.a (flowering date vs. temperature*species + stations (RANDOM EFFECT))

lm3.a <- lmer(day ~ mean_annual_temp*species_name + (1|station_name), data = flower_temp_data, REML = FALSE)   
summary(lm3.a)
```

# RANDOM EFFECT B: (1|island)
```{r}
#Model 1.b (flowering date vs.  temperature + islands (RANDOM EFFECT))
lm1.b <- lmer(day~mean_annual_temp + (1|island), data=flower_temp_data)
summary(lm1.b)

```

```{r}
#Model 2.b (flowering date vs. species + islands (RANDOM EFFECT))
lm2.b <- lmer(day~species_name + (1|island), data=flower_temp_data)
summary(lm2.b)
```

```{r}
#Model 3.b (flowering date vs.  temperature *species + islands (RANDOM EFFECT))
lm3.b <- lmer(day~mean_annual_temp * species_name + (1|island), data=flower_temp_data)
summary(lm3.b)
```
# RANDOM EFFECT C: (1|island/station_name)

```{r}
#Model 1.c (flowering date vs. temperature + (1|island/station_name) (RANDOM EFFECT))

lm1.c <- lmer(day ~ mean_annual_temp + (1|island/station_name), data = flower_temp_data, REML = FALSE)   
summary(lm1.c)
```

```{r}
#Model 2.c (flowering date vs. species + (1|island/station_name) (RANDOM EFFECT))

lm2.c <- lmer(day ~ species_name + (1|island/station_name), data = flower_temp_data, REML = FALSE)   
summary(lm2.c)
```

```{r}
#Model 3.c (flowering date vs. temperature*species + (1|island/station_name) (RANDOM EFFECT))

lm3.c <- lmer(day ~ mean_annual_temp*species_name + (1|island/station_name), data = flower_temp_data, REML = FALSE)   
summary(lm3.c)
```

#run AICc
```{r}
result <- AICc(lm1, lm2, lm3, lm1.a, lm1.b, lm1.c, lm2.a, lm2.b, lm2.c, lm3.a, lm3.b, lm3.c)
result
```

```{r}
result[which.min(result$AICc),]
```

#lm3.b is the best model.

```{r}
#create a model for lm3.b (flowering date vs.  temperature*species + islands (RANDOM EFFECT))
flower_temp_data <- flower_temp_data %>% 
  mutate(lm3.b.pred = predict(lm3.b)) #add predicted values to dataset

lm3.b.fig <- flower_temp_data %>% 
  ggplot(aes(x = mean_annual_temp, y = day, colour = species_name)) +
  theme_classic() +
  facet_wrap(~island) +
  labs(x = "Mean Annual Temperature (Degrees Celsius)", 
       y = "First Flowering Date (Predicted Data)", 
       colour = "Species" ) +
  
#Add fitted values (i.e., regression lines)
  geom_line(aes(y = lm3.b.pred), size = 1) +
  geom_point(size = 1.2, alpha = 0.5)

lm3.b.fig
```
```




